### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by glamble007** [siteoptimo/woocommerce-plivo#4]
Fatal error: Call to a member function getVariables() on a non-object in /home/urbanltd/public_html/wp-content/plugins/woocommerce-plivo/includes/admin/wcp-admin-setting-fields.php on line 96

**Comment by vdwijngaert** [comment]
Hello glamble007,

Unfortunately, we were unable to reproduce your problem. Everything is working as expected over here. I've gone over the code a few times now, but I can't see a single reason why this shouldn't work on your setup. 

But, error messages don't lie. We're very curious to find out why this error is being thrown, so we would like to take a look at the problem ourselves, if that's okay for you.

Would you be so kind as to provide us with FTP details and a WordPress account with access to the WooCommerce settings pages? This can be to your live environment, but if you don't want that, you can also take a copy of your current setup and we'll work from there.

You can email it to me at koen@siteoptimo.com. 

Thanks,

Koen

**Comment by glamble007** [comment]
I fixed the issue myself. Solution is:

If($sh){
GetVariables....
}

**Comment by vdwijngaert** [comment]
Hello Glamble007,

That is only a temporary workaround, because _$sh_ should never be null. There are other pieces of code that rely on the status hooks, so they may break too.

My offer still stands.

Regards,

Koen

**Comment by glamble007** [comment]
Well the code means if $sh is valid then only go ahead else skip. Makes
sense I guess?

**Comment by vdwijngaert** [comment]
I've been able to find the issue. Because the settings fields were not filled in, the status hooks were not being loaded. Fixed this in the new release.

Thanks for bringing this to the light!

**Comment by glamble007** [comment]
You are welcome! Again the new phone number hook you have implemented, have
you put a validation to it or not? If that prefix is already present, there
is no need to add it country code. Otherwise it will be a mess.

This is what my current modified code looks like and works fine.

public function sendText($to, $message)
    {
if (substr($to, 0, 3) === '+91'){
 $params = array('src' => self::$from, 'dst' => $to, 'text' => $message,
'type' => 'sms');
}
else if (substr($to, 0, 2) === '91'){
$params = array('src' => self::$from, 'dst' => $to, 'text' => $message,
'type' => 'sms');
}
 else {
        $params = array('src' => self::$from, 'dst' => '+91'.$to, 'text' =>
$message, 'type' => 'sms');
}
